import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { Footer } from "@/components/footer";
import { GlobalBackground } from "@/components/global-background";
import { PagePrefetcher } from "@/components/page-prefetcher";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ChatbotFloating } from "@/components/shell/chatbot-floating";
import { ChatProvider } from "@/context/chat-context";
import { CartProvider } from "@/context/cart-context";
import { Toaster } from "@/components/ui/sonner";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              if ('scrollRestoration' in history) {
                history.scrollRestoration = 'manual';
              }
              if (window.location.hash) {
                history.replaceState(null, '', window.location.pathname + window.location.search);
              }
              window.scrollTo(0, 0);
            `,
          }}
        />
      </head>
      <body
        className={`${inter.variable} font-sans antialiased relative min-h-screen`}
      >
        <ChatProvider>
          <CartProvider>
            <GlobalBackground />
            <PagePrefetcher />

            <Header />
            {children}
            <ChatbotFloating />
            <Footer />
            <Toaster position="top-right" />
          </CartProvider>
        </ChatProvider>
      </body>
    </html>
  );
}
