import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { Footer } from "@/components/footer";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} font-sans antialiased relative min-h-screen`}
      >
        {/* Contenedor de fondo asegurado como FIJO */}
        <div className="fixed inset-0 -z-10 w-full h-dvh overflow-hidden bg-white pointer-events-none will-change-transform">
          <img
            src="/Background.svg"
            alt=""
            className="w-full h-full object-cover object-left  opacity-70 sm:opacity-40 pointer-events-none"
          />

          <div className="absolute inset-0 backdrop-blur-[60px] sm:backdrop-blur-[100px] backdrop-saturate-250 sm:backdrop-saturate-200 pointer-events-none" />

          <div className="absolute inset-0 bg-[#0057FF]/15 backdrop-brightness-95 sm:backdrop-brightness-100 sm:bg-transparent pointer-events-none" />
        </div>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
