import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { Footer } from "@/components/footer";
import Image from "next/image";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} font-sans antialiased relative min-h-screen`}
      >
        {/* Global Top Background Layer */}
        <div className="absolute top-0 left-0 w-full h-[1400px] -z-10 overflow-hidden pointer-events-none">
          <div className="relative w-full h-full">
            <Image
              src="/background.png"
              alt=""
              fill
              className="object-cover object-top scale-150 lg:scale-[1.3] opacity-100"
              priority
            />
            {/* Extended Bottom Fade to integrate with sections below */}
            <div className="absolute inset-x-0 bottom-0 h-[30%] bg-linear-to-t from-white via-white/50 to-transparent" />
          </div>
        </div>

        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
